version: '3.11'

services:
  autodet-postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: autodet
      POSTGRES_PASSWORD: autodet
      POSTGRES_DB: autodet
    volumes:
      - autodet_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  celery-worker:
    container_name: celery-worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      DB_HOST: postgres
    command: "celery -A mysite.celery worker --loglevel=INFO"

  celery-beat:
    container_name: celery-beat
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - celery-worker
      - web
    environment:
      DB_HOST: postgres
    command: "celery -A mysite.celery beat --loglevel=INFO"


  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - autodet-postgres-db
      - redis

volumes:
  autodet_postgres_data:

